name:                rps-game-haskell
version:             0.1.0.0
github:              "hpemaoff/rps-game-haskell"
license:             BSD3
author:              "Martin Offermann"
maintainer:          "hpemaoff@gmail.com"
copyright:           "Martin Offermann"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hpemaoff/rps-game-haskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  rps-game-haskell-exe:
    main:                RPS.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rps-game-haskell
    - random

tests:
  rps-game-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rps-game-haskell
    - random
